options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: 'projects/$PROJECT_ID/locations/asia-east1/workerPools/cloud-build-vm-1'
steps:
  - name: 'kuoche1712003/java:17'
    entrypoint: 'bash'
    args: ['-c', './mvnw package -DskipTests -Dnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true -Dquarkus.container-image.group=asia-east1-docker.pkg.dev -Dquarkus.container-image.name=$PROJECT_ID/rmn/java-test']
images:
  - "asia-east1-docker.pkg.dev/$PROJECT_ID/rmn/java-test"