options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: 'projects/$PROJECT_ID/locations/asia-east1/workerPools/cloud-build-vm-1'
steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'apt install -y openjdk-17-jdk && ./mvnw package -DskipTests -Dquarkus.container-image.build=true -Dquarkus.container-image.group=asia-east1-docker.pkg.dev -Dquarkus.container-image.name=$PROJECT_ID/rmn/java-test -Dquarkus.container-image.tag=$SHORT_SHA && docker push asia-east1-docker.pkg.dev/$PROJECT_ID/rmn/java-test:$SHORT_SHA' ]